default_stages: [commit, push]
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # check and format the syntax
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: double-quote-string-fixer
      # environment checker
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # check the git-related commit or object
      - id: check-merge-conflict
      # check sensitive information
      - id: debug-statements
      - id: detect-private-key
        exclude: (tests/|.*\/tests\/.*)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: ["--py311-plus"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: import-linter
        name: Import Linter (Clean Architecture Boundaries)
        files: '^src/horizon/.*\.py$'
        pass_filenames: false
        language: python
        additional_dependencies: [import-linter>=2.0]
        entry: bash -c 'PYTHONPATH=src lint-imports --verbose'
